# Generated by Django 4.2 on 2023-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
    ]
